### ISSUE TITLE
Implement authentication via social providers

### ISSUE THREAD

**Issue by squidfunk** [squidfunk/terraform-aws-cognito-auth#1]
# Social Login

> Disclaimer: I'm not an expert in this topic, but I'm happy to work together on this to improve the experience for everyone

This issue's purpose is the documentation of my findings regarding the implementation of authentication using 3rd party identity providers, namely Facebook, GitHub etc., as this is a feature that would be really great and helpful. However, it turns out to be rather tricky.

## Acceptance criteria

From my point of view, an implementation of this feature must fulfill the following requirements:

1. The user can sign in via Facebook, Google and GitHub, as I regard them to be the most prominent providers
2. The user doesn't see Cognito's hosted UI during registration and authentication, meaning redirects through the Cognito User Pool domain are okay, but displaying the hosted UI is not
3. The user should receive a JWT token (ID, Access), not AWS credentials
4. The user can use the JWT token to make calls to a protected API Gateway resource
5. The user has a corresponding record in our Cognito User Pool, so we can attach further data and have a unique identifier for identifying the user inside our application

### Using Federated Identities

Using federated identities, we could easily implement Facebook login or login with any other OpenID connect provider. For example using the AWS CLI:

```
aws cognito-identity get-id \
  --identity-pool-id $POOL_ID
```

This will return an identity identifier which we can then use to request an OpenID token:

```
aws cognito-identity get-open-id-token \
  --identity-id $ID \
  --logins graph.facebook.com=$TOKEN
```

To my knowledge this approach has the following problems:

1. The OpenID token that is returned by the last call cannot be used to authenticate users using a Cognito User Pool authorizer in front of API Gateway as Identity Pools and User Pools are two separate things. We would have to roll our own custom authorizer in form of a Lambda function and verify the token by ourselves __(violates 4.)__
2. The user doesn't have a corresponding entry in our User Pool, as Identity Pools and User Pools would share no connection __(violates 5.)__

### Using the OAuth endpoints

Cognito User Pools added a feature quite recently which allows to use external federated identity providers directly. However, this means we would have to do the OAuth dance ourselves and use the hosted UI for this purpose, as there seems to be now support within the SDK to associate a Facebook access token which was gathered through the client-side Facebook SDK with a User Pool ID token.

Also we would have to expose the link to the hosted UI in the frontend, as it proxies the redirect to Facebook and encapsulates the authorization process using authorization code grant (e.g.):

``` bash
GET "https://$DOMAIN.auth.us-east-1.amazoncognito.com/oauth2/authorize?response_type=code&client_id=$CLIENT_ID&redirect_uri=$APP_DOMAIN&state=$STATE&identity_provider=Facebook&scope=email"
```

When the user has authorized the application he will be redirected to:

``` bash
GET "https://$APP_DOMAIN/?code=$CODE&state=$STATE"
```

The code would then have to be exchanged using the `TOKEN` endpoint:

``` bash
POST "https://$DOMAIN.auth.us-east-1.amazoncognito.com/oauth2/token?grant_type=authorization_code&client_id=$CLIENT_ID&code=$CODE&redirect_uri=$APP_DOMAIN"
```

This approach has the following problems:

1. From my testing there's no ID token returned, so we would definitely have to use OAuth scopes inside our API Gateway-hosted API. I don't really know if that could be a good thing in general ditching the ID-token approach and sticking with Access tokens, maybe someone can comment __(violating 4.)__ __UPDATE: The ID token is returned if the `openid` scope is requested__
2. The Client ID would need to be public which should be fine in general, but currently it's entirely hidden behind API Gateway, so even nicer.
3. I'm not sure whether GitHub integration is possible as it's not supported out of the box, but it should in theory be possible with the generic OpenID provider implementation __(might violate 1.)__
4. Another problem is that the refresh token is directly returned within the response. I've been testing with the __Authorization Code Grant__ which is actually not suited for web applications because it returns the refresh token in the response and not in a secured cookie. However, we would just expose an API Gateway endpoint that makes the call to the `TOKEN` endpoint and encodes the refresh token in a cookie, so that shouldn't be a problem.

## Questions

1. How do we solve authentication for Social Login providers?
2. Should we use resource servers and OAuth scopes and stick to access tokens for the User Pools authorizer? [This comment](https://stackoverflow.com/questions/50404761/aws-api-gateway-using-access-token-with-cognito-user-pool-authorizer/50617345#50617345) has some guidelines regarding the implementation
3. How do we handle users that use Facebook and want to switch to username+password later (or the other way around)?

**Comment by jimbol** [comment]
This would be pretty nice to have for my application. Has there been any development here?

**Comment by squidfunk** [comment]
Nope, currently there's no plan to implement this (in my spare time).
