### ISSUE TITLE
authorization header is malformed: us-east-1 is wrong expecting us-west-2

### ISSUE THREAD

**Issue by reelsense** [squidfunk/terraform-aws-cognito-auth#1052]
## Description

```
module "cognito-auth" {
  source  = "squidfunk/cognito-auth/aws"

  region                         = "us-east-1"

```

Setting region to `"us-east-1"` fails, `Error: Error creating S3 bucket: AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'`.

### Expected behavior

I expect the region set in the module to change the region appropriately for all everything under the module.

### Actual behavior

```
Error: Error creating S3 bucket: AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'
	status code: 400, request id: FCFE15E11F4B83F0, host id: iisIYoUBb4qGe3I57Ey5ap1WkSGk3OoMHbKi9iBelQjz5bzJaEAGx040heQMki2AfTwsXX1cSro=

  on .terraform/modules/aws-us-east-1.cognito-auth/squidfunk-terraform-aws-cognito-auth-77a1796/modules/web/main.tf line 145, in resource "aws_s3_bucket" "_":
 145: resource "aws_s3_bucket" "_" {
```

### Steps to reproduce the bug

1. Change the region in the module to `us-east-1`
2. `terraform init`
3. `terraform apply`

### Package versions

* terraform-aws-cognito-auth: `0.4.2`
* terraform: `0.12.20`

### System information

* OS: Ubuntu 16.04

**Comment by squidfunk** [comment]
Very weird. I have successfully deployed this module in different regions. I actually cannot reproduce the error. Can you provide a repository with a minimal test case?

**Comment by squidfunk** [comment]
Could be related to https://github.com/hashicorp/terraform/issues/2774. Could you try and specify an alternative name for the bucket? Reading the linked issue it sounds as if the bucket name may be already taken.

**Comment by reelsense** [comment]
I think you're correct it's related to https://github.com/hashicorp/terraform/issues/2774. If I forget to update this thread then that solved my problem.

**Comment by reelsense** [comment]
I confirmed that this was the problem. I added a note for my future self in my module so I don't forget. I was using an account with many s3 buckets so there was a good chance of name collision.

```hcl
  source  = "squidfunk/cognito-auth/aws"
  
  namespace                      = "exampledev"  # cannot collide with any s3 bucket name
```

**Comment by squidfunk** [comment]
AWS error message can be very cryptic at times 😄
