### ISSUE TITLE
Build issue on amazonlinux image

### ISSUE THREAD

**Issue by avanzarit-in** [squidfunk/terraform-aws-cognito-auth#1173]
## Description
Getting multiple build issues and test case failures while building.
[Description of the bug]

### Expected behavior

[What you expected to happen]

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Package versions

* terraform-aws-cognito-auth: `...`
* terraform: `...`

### System information

* OS: amazonlinux
* NodeJS: 13.0.13
* Typescript: 3.8.3

**Comment by squidfunk** [comment]
We’re gonna need a little more than that 😅

**Comment by squidfunk** [comment]
Closing due to missing information.
