### ISSUE TITLE
Building messages

### ISSUE THREAD

**Issue by marsouin** [squidfunk/terraform-aws-cognito-auth#1184]
## Description

Huge node modules and puppeteer download when building. Also there is no index.js in the resulting dist.zip archive. 

### Expected behavior

dist.zip to be small

### Actual behavior

dist.zip weighs about 6.5mo

### Steps to reproduce the bug

1. make build

### Package versions

* terraform-aws-cognito-auth: `latest`

### System information

* OS: MacOS

**Comment by squidfunk** [comment]
You’re free to PR to improve on bundle size 😊 currently short on time.

**Comment by marsouin** [comment]
Sorry, I might have been unclear, I was merely surprised the zip provided in the repo is ~150k, whereas mine goes up to 6.5mo. Any idea why? The node_modules I have is much larger than yours.

**Comment by squidfunk** [comment]
I can confirm that the size of `dist.zip` is now 5.6mb. However, I do not have the time to debug why. When I run `ncdu` on the zip, it seems like `core-js` and some other unnecessary dependencies have been pulled in. The direct dependencies haven't changed:

``` json
  "dependencies": {
    "mime": "^2.4.4",
    "mimemessage": "^1.0.5",
    "mustache": "^4.0.1",
    "quoted-printable": "^1.0.1"
  }
```

For this reason, I assume that one of the transitive dependencies got updated, which leads to an increase in size. Happy to merge PRs.

**Comment by marsouin** [comment]
I will have a look and PR if I find something ;)
