### ISSUE TITLE
Unable to terraform apply

### ISSUE THREAD

**Issue by jjkirkpatrick** [squidfunk/terraform-aws-cognito-auth#1329]
## Description

When doing terraform apply I'm getting the following errors. 

Error: Error running command '.terraform/modules/cognito-auth/terraform-aws-cognito-auth-0.4.2/modules/web/s3/scripts/sync.sh': exit status 1. Output: fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

Error: Error creating Lambda function: AccessDeniedException: 
        status code: 403, request id: cbe2020f-da7c-436f-a16d-ffe0d833fc94

  on .terraform/modules/cognito-auth/terraform-aws-cognito-auth-0.4.2/modules/web/main.tf line 319, in resource "aws_lambda_function" "_":
 319: resource "aws_lambda_function" "_" {

`module "cognito-auth" {
  source  = "squidfunk/cognito-auth/aws"
  version = "0.4.2"

  namespace                      = "auth-j***k"
  region                         = "eu-west-1"
  cognito_identity_pool_name     = "auth pool"
  cognito_identity_pool_provider = "auth.j***k.co.uk"

  # Optional: Default UI
  app_hosted_zone_id  = "Z0***********6F"
  app_certificate_arn = "arn:aws:acm:eu-west-1:956613166899:certificate/4f86bc3d-32af-4b75-bf07-3ea7d2874787"
  app_domain          = "auth.jj***kk.co.uk"
  app_origin          = "j***k.co.uk"

  # Optional: Email delivery
  ses_sender_address = "j***@***.co.ukk"
}
`

The IAM policy used to create the resources is using the AWS manages policy 'AdministratorAccess'

### Package versions

* terraform-aws-cognito-auth: `0.4.2`
* terraform: `Terraform v0.12.29`

### System information

* OS: Ubuntu running on WSL

**Comment by squidfunk** [comment]
Does your user have the adequate permissions? Sounds like an issue with your IAM roles.

**Comment by jjkirkpatrick** [comment]
The user that is running the terrafrom apply has the following IAM policy. 

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}`

**Comment by jjkirkpatrick** [comment]
I have gotten it to work.

I had to manually update the provider in modules/web/main.tf to
`provider "aws" {
  version    = ">= 2.0.0"
  alias      = "lambda"
  region     = "us-east-1"
  access_key = "AK------------------G"
  secret_key = "yW-----------------------------k"
}`

Looks like it wasn't picking up my creds, i had tried EXPORT'ing them, and aws configure, might be something to do with running Ubuntu on WSL2 instead of natively. 

Not sure, Closing the issue as i don't believe it's an issue with the project.
