### ISSUE TITLE
What if I have multiple target domain? Very common to have multiple client app using the same pool

### ISSUE THREAD

**Issue by junaryanto** [squidfunk/terraform-aws-cognito-auth#1658]
## Description

Currently the setup only allow one target domain. I want to have multiple target domain. 

### Expected behavior

Allows for multiple target domain, and redirect passed on as parameter

**Comment by squidfunk** [comment]
Thanks for suggesting! Care to submit a PR? 😊

**Comment by squidfunk** [comment]
Closing as out-of-scope.
