### ISSUE TITLE
Switch to new AdminSetUserPassword API

### ISSUE THREAD

**Issue by davidmortiz** [squidfunk/terraform-aws-cognito-auth#411]
Just an FYI as someone who's been waiting for this feature for a while I noticed that Cognito finally released an API that gives you the ability to change a user's password for them.

https://aws.amazon.com/about-aws/whats-new/2019/05/amazon-cognito-launches-enhanced-user-password-reset-api-for-administrators/

Hopefully, this will help address one of the major limitations.  If I have time later maybe I'll submit my own PR.

**Comment by squidfunk** [comment]
That's great news! Thanks for pointing it out. Will integrate it when I find some time!

**Comment by squidfunk** [comment]
Trickier than expected: `AdminSetUserPassword` was added to the JavaScript SDK in [2.449.0](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#24490). Both [node runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) (8.10 and 10.15) include older SDK versions, which means we would need to bundle the SDK with the Lambda function . This is, of course, possible, but when I started doing this and ran into other problems – changing the password did not work. For this reason I would want to wait until one of the runtimes includes the newer SDK and AWS fleshed the bugs out.

I'll leave this open and revisit it at some point in the future. Nevertheless, thanks for pointing it out! Have been waiting for this for ages! It'll make this project much more robust.

**Comment by squidfunk** [comment]
[Node.js runtimes have been updated to 2.488.0](https://docs.aws.amazon.com/de_de/lambda/latest/dg/lambda-runtimes.html), so the SDK now supports `AdminSetUserPassword`. We need to switch to Node 10 anyway, so this issue can and should be tackled.

**Comment by squidfunk** [comment]
See https://github.com/squidfunk/terraform-aws-cognito-auth/commit/a5f8a9b2f9ac7ccbc4e8138304873770362b37cb#commitcomment-35890128 for a guide to integrate this until I find the time to merge it into master. PRs welcome.

**Comment by rafaelsiqueira** [comment]
Hi guys! I've just created the PR based on the `refactor/change-password` branch. I appreciate if you guys could invest some time to review it, and if it's okay, merge it to master.

Thanks for creating this "boilerplate". It's being an awesome shortcut for our auth solution here.

Cheers!
