### ISSUE TITLE
Open discussion on overall design of serverless system using terraform

### ISSUE THREAD

**Issue by ziedbouf** [squidfunk/terraform-aws-cognito-auth#612]
Thanks @squidfunk  for the project, it illustrate in beautiful manner how to implement serverless architecture in terraform. Some questions i have in mind that i would like to implement for one of our internal project.  The main idea is to use serverless infrastructure for set of machine learning models that will be served through lambda/sagemaker. 

Some modules are required in order to have the product up and running are:
-  Billing system to count the users usage of the system. 
-  User management including registration and activation of users using admin super users role.
- Monitoring of the system and logging for auditing purpose.

@squidfunk  is it possible to share some thoughts on how do you think is right set of solution to use combining terraform-aws-cognito-auth part of the system?

**Comment by squidfunk** [comment]
@ziedbouf the one thing this project delivers is reliable user registration and login, as well as a customizable registration flow. Its responsibility ends when the user signed in and received the ID token. For example, in a client project, I've deployed a GraphQL API on API Gateway which is secured with a Cognito User Pool, so after the user registered, confirmed his account and signed in, he's redirected to the admin backend where the ID token is used to communicate with GraphQL via XHR. When the token expires, the admin backend redirects back to the auth page where a refresh token is used to automatically refresh the session.

Everything else depends on your use case, business requirements and architecture.

**Comment by ziedbouf** [comment]
thanks @squidfunk  i agree with you on the scope of the project however do you advise in any way how to integrate this with third party  party we just treat it as terraform module and that's all.

**Comment by squidfunk** [comment]
basically yes, but of course your milage may vary.

**Comment by ziedbouf** [comment]
thanks @squidfunk.
