### ISSUE TITLE
jq dependency 

### ISSUE THREAD

**Issue by zthomas** [squidfunk/terraform-aws-cognito-auth#901]
## Description
in terraform apply I'm seeing an error

### Expected behavior
show the Terraform plans
```
terraform apply
```

### Actual behavior
Throws an error
```
.terraform/modules/cognito-auth/squidfunk-terraform-aws-cognito-auth-77a1796/modules/web/s3/scripts/trigger.sh: line 36: jq: command not found
```

### Steps to reproduce the bug
Follow the instructions in the readme and create use the module provided. Ensure to include `app_hosted_zone_id` and the default UI configs

### Package versions

* terraform-aws-cognito-auth: `0.4.2`
* terraform: `0.12.13`

### System information

* OS: [The operating system you're running]
* Anything else relevant

**Comment by squidfunk** [comment]
Jep, `jq` is a dependency for the S3 trigger to sync the assets for the webapp. Should probably be noted in the docs. Happy to merge PRs!

**Comment by rafaelsiqueira** [comment]
@zthomas @squidfunk I've created a PR to help with this.
